PACKAGE=        lua
PKGVER=         5.4.4-r1
DESCRIPTION=    "Lua interpreter and compiler"
PACKAGER=       micro systems <info@msys.ch <info@msys.ch>>
URL=            https://lua.msys.ch
MAINTAINER=     micro systems <info@msys.ch>
LICENSE=        MIT

FILES=          usr/bin/lua \
                usr/bin/luac

MKDIR?=         ../../mk/

include $(MKDIR)alpine.package.mk
