# From https://lists.alpinelinux.org/~alpine/apk-tools/%3CD194B900-6A60-4A2C-B520-513D8F1263D6%40msys.ch%3E

LICENSE?=       custom
PACKAGER?=      unknown
DESCRIPTION?=   unknwon
PACKAGER?=      unknown
URL?=           unknown
MAINTAINER?=    unknown

INSTSCRIPTS!=   find . -name .p\*-\*install -exec basename {} \;
DATE_EPOCH!=    date -u "+%s"

.DEFAULT_GOAL=  package

package:
        # Create the data part
        @-mkdir -p staging
        @tar -C /tmp/alpine -f - -c ${FILES} | tar -C staging -x

        find staging -exec touch -h -d @${DATE_EPOCH} {} +

        # @(cd staging; tar --xattrs -f - -c *) | abuild-tar --hash | \
        #        gzip > data.tar.gz

        (cd staging; find . -print0) | LC_ALL=C sort -z | tar -C staging --xattrs \
                        --xattrs-exclude=security.selinux \
                        --format=posix \
                        --pax-option=exthdr.name=%d/PaxHeaders/%f,atime:=0,ctime:=0 \
                        --mtime="@${DATE_EPOCH}" \
                        --no-recursion --null -T - \
                        -f - -c | abuild-tar --hash | gzip -n -9 >data.tar.gz

        # Create .PKGINFO
        @echo "# Generated by alpine.package.mk" > .PKGINFO
        @echo -n "# " >> .PKGINFO
        @date >> .PKGINFO
        @echo "pkgname = ${PACKAGE}" >> .PKGINFO
        @echo "pkgver = ${PKGVER}" >> .PKGINFO
        @echo "pkgdesc = ${DESCRIPTION}" >> .PKGINFO
        @echo "url = ${URL}" >> .PKGINFO
        @echo "builddate = ${DATE_EPOCH}" >> .PKGINFO
        @echo "commit = 5ff2c19564c162690aa5abbfb46fd6d3960c1c24" >> .PKGINFO
        @echo "packager = ${PACKAGER}" >> .PKGINFO
        @echo -n "size = " >> .PKGINFO
        @(cd staging; du -b -c ${FILES}) | tail -n 1 | cut -f 1 >> .PKGINFO
        @echo "arch = x86_64" >> .PKGINFO
        @echo "origin = ${PACKAGE}" >> .PKGINFO
        @echo "maintainer = ${MAINTAINER}" >> .PKGINFO
        @echo "license = ${LICENSE}" >> .PKGINFO
        @for dep in ${DEPENDS}; do echo "depend = $${dep}" >> .PKGINFO; done
        @echo "# automatically detected:" >> .PKGINFO
        @for f in ${FILES}; \
        do \
                find /tmp/alpine -name $${f} -type f -perm +111; \
                echo -n "provides = cmd:" >> .PKGINFO; \
                basename $${f} | tr -d '\n' >> .PKGINFO; \
                echo "=${PKGVER}" >> .PKGINFO; \
        done
        @echo -n "datahash = " >>.PKGINFO
        @sha256sum data.tar.gz | cut -d " " -f 1 >> .PKGINFO

        # Create the control part (index)
        tar --format=posix \
                --pax-option=exthdr.name=%d/PaxHeaders/%f,atime:=0,ctime:=0 \
                --mtime="@${DATE_EPOCH}" \
                -f - -c .PKGINFO ${INSTSCRIPTS} | abuild-tar --cut \
                | gzip -n -9 > control.tar.gz


        #@tar --owner=0 --group=0 --numeric-owner -c .PKGINFO ${INSTSCRIPTS} | \
        #       abuild-tar --cut | gzip > control.tar.gz
        @abuild-sign -q control.tar.gz

        # Produce the final apk
        @cat control.tar.gz data.tar.gz > ${PACKAGE}-${PKGVER}.apk
        @cat control.tar.gz data.tar.gz > /var/apk/${PACKAGE}-${PKGVER}.apk
        -(cd /var/apk; apk index ${PACKAGE}-${PKGVER}.apk -o APKINDEX.tar.gz)
        abuild-sign -q /var/apk/APKINDEX.tar.gz

        # Show info and clean up
        @cat .PKGINFO
        @rm -rf data.tar.gz control.tar.gz .PKGINFO staging
